<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<h1>Hello, world!</h1>

<button type="button" class="btn btn-primary">Test Button</button>
<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <a href="/" class="list-group-item list-group-item-action fw-bold">Всі категорії</a>
            <a href="/category/LAPTOPS" class="list-group-item list-group-item-action">💻 Ноутбуки та комп'ютери</a>
            <a href="/category/SMARTPHONES" class="list-group-item list-group-item-action">📱 Смартфони, ТВ і електроніка</a>
            <a href="/category/GAMING" class="list-group-item list-group-item-action">🎮 Товари для геймерів</a>
            <a href="/category/HOME_APPLIANCES" class="list-group-item list-group-item-action">🏠 Побутова техніка</a>
            <a href="/category/HOME" class="list-group-item list-group-item-action">🛋️ Товари для дому</a>
            <a href="/category/BEAUTY" class="list-group-item list-group-item-action">💄 Краса та здоров'я</a>
            <a href="/category/SPORT" class="list-group-item list-group-item-action">🏀 Спорт і захоплення</a>
            <a href="/category/KIDS" class="list-group-item list-group-item-action">🧸 Дитячі товари</a>
            <a href="/category/BOOKS" class="list-group-item list-group-item-action">📚 Офіс, школа, книги</a>
        </div>
    </div>

    <div class="col-md-9">
        <!-- Здесь уже твои карточки с товарами -->
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>